Travis : Update ruby to 2.4
Hopefully this gets rid of the following error :

```
ERROR:  Error installing html-proofer:

	parallel requires Ruby version >= 2.4.
```

We should move this to GitHub Actions too, but it's teatime now.